menu:
    Archive: /archives/
    Rss: /atom.xml
    Github: https://github.com/0jinxing

favicon: /favicon.ico
logo: /favicon.ico

highlight:
  enable: false
  
# Copyright Infomation
startyear: 2017
